language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
os:
  - linux
  # osx doesn't support Python yet
install:
  - pip install pylint
before_script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export PYGNURL_LIB=libreadline.so.6; fi
  # when osx is supported, will need to brew install readline
script:
  - pylint pygnurl -d locally-disabled -r n
  - pylint tests -d locally-disabled -r n
  - python -m unittest discover tests
  - python setup.py sdist bdist_wheel
